Anonymous Web SDK connection to domain server
vircadia/vircadia-web-sdk pull request #23
Opened 2021-07-30 10:03 UTC by ctrlaltdavid

`DomainServer` API additions:
- `connect(url)`: WebSocket URL for the Doman Server's WebRTC signaling WebSocket port, e.g., `ws://127.0.0.1:40102`.
- `disconnect()`
- `location`: Read-only property returning the current location URL.
- `state`: Read-only property returning the current connection state.
- `DISCONNECTED` etc.: Read-only properties of connection state values.
- `refusalInfo`: Read-only property with description of connection `REFUSED` state.
- `errorInfo`: Read-only property with description of connection `ERROR` state.
- `onStateChanged`: Write-only property that sets a callback function to be called when the connection state changes.

Builds on top of PR https://github.com/vircadia/vircadia-web-sdk/pull/20.
Works in conjunction with Vircadia PR https://github.com/vircadia/vircadia/pull/1300.

Merge sequence:
- [ ] PR https://github.com/vircadia/vircadia-web-sdk/pull/20.
- [ ] CR, QA.
- [ ] Merge.

#### QA
- `npm run lint` - Should complete with no errors.
- `npm run build` - Should complete with no errors.
- `npm run test` - All  tests should pass. 
    Run the tests against the domain server in https://github.com/vircadia/vircadia/pull/1300.
    Known issue: "Jest did not exit one second after the test run has completed." See: https://github.com/vircadia/vircadia-web-sdk/issues/21
- `npm run devdoc` : Docs should be created in `./docs/dev/` directory.
- `npm run sdkdoc` : Docs should be created in `./docs/sdk/` directory.

2021-08-13 04:40 UTC, ctrlaltdavid commented on src/DomainServer.ts
> +        if (typeof callback === "function" || callback === null) {
Per the JSDoc, the value values are a function or `null`: "Sets a single function to be called when the state of the domain server connection changes. Set to null to remove the callback."
A value of `undefined` would be an error on the user script's part, and this is caught with an error message logged and the property value set to ``null`.
The JSDoc does need a minor update, thought to explicitly show that `null` is a valid value.

2021-08-13 04:52 UTC, ctrlaltdavid commented on src/DomainServer.ts
> +    static get DISCONNECTED(): ConnectionState {
`DomainServer` is part of the public API. I envisage a JavaScript Web client doing things such as ...
```
if (DomainServer.state === DomainServer.CONNECTED) {
    ...
}
```

An alternative could be ...
```
if (DomainServer.state === DomainServer.states.CONNECTED) {
    ...
}
```
... though I don't know that this is an improvement. It seems a little less immediate?

Assignment client APIs may well have similar states.

2021-08-13 05:03 UTC, ctrlaltdavid commented on src/domain/networking/DomainHandler.ts
> +    setIsConnected(isConnected: boolean, forceDisconnect = false): void {
Yes, `forceDisconnect` is an optional parameter of type `boolean` and default value of `false`.
If `forceDisconnect?: boolean` is used the parameter type becomes `boolean | undefined`, which is not wanted.
If `forceDisconnect? = false` is used the parameter type becomes `boolean | undefined` and you get a TypeScript error, "Parameter cannot have question mark and initializer".
... So, no change.

2021-08-13 16:40 UTC, Misterblue approved these changes
JS has made it confusing with both 'undefined' and 'null' but the code doesn't fail in either case and the documentation specifies what it should be.

2021-08-15 22:14 UTC, digisomni requested changes

2021-08-16 03:26 UTC, ctrlaltdavid commented on src/domain/networking/DomainHandler.ts
> +        console.log("[networking] Disconnecting from domain server.");
Quite possibly.

2021-08-16 03:31 UTC, ctrlaltdavid commented on tests/DomainServer.unit.test.js
> +        domainServer.connect("  ");
Doesn't matter. I'll make it 0 spaces so as not to cause confusion.

2021-08-16 03:40 UTC, digisomni approved these changes

2021-08-16 03:52 UTC, digisomni commented
Test suites passed.

2021-08-16 03:52 UTC, merged