Update audio input resampling code; improves Firefox support.
vircadia/vircadia-web-sdk pull request #43
Opened 2021-10-13 19:35 UTC by namark

~~needs more work to either move most of the processing out of the worklet, or hand roll a resampling algorithm.~~

QA
Should include comparing before and after on Edge/Chromium to see whether or not audio has noticeably more glitches.

2021-10-15 20:24 UTC, namark commented
Yes, I agree that with the hand rolled version it makes more sense to do everything in one go in the worklet. I would prefer to continue on this branch to not loose track of things, if you don't mind my back and forth commits :D
 
I'll definitely need to take care of the left over/alignment issue as well, but for testing purposes with the chosen target buffer size and sample rate things seem to actually line up perfectly. For example in case of 44100 to 24000 downsampling, it would buffer every 441 samples then downscale to 240, and you'd always get something similar as long as the source sample rate is a multiple of a 100 I believe. I'll see what I can come up with for a more general case, maybe there is some clever way to avoid floating point errors as well, based on the choice of the buffer size.

2021-10-19 23:22 UTC, ctrlaltdavid commented on src/domain/audio/AudioInput.ts
> -
It would be good to reinstate these removed blank lines because they help delineate between the different types of methods.

2021-10-19 23:41 UTC, ctrlaltdavid commented on src/domain/audio/AudioInput.ts
> +
Please add a comment on what this code does, i.e., if a browser doesn't automatically handle sample rate conversion then create an audio context at the hardware rate and handle the sample rate conversion for mic input in the audio worklet.
> Uncaught (in promise) DOMException: AudioContext.createMediaStreamSource: Connecting AudioNodes from AudioContexts with different sample-rate is currently not supported.

Aside; I wonder why sample rate conversion isn't required for audio output - unless that just happens to be 24kHz in on our test PCs.

2021-10-19 23:46 UTC, ctrlaltdavid commented on src/domain/worklets/AudioInputProcessor.ts
> + */
```suggestion
// See: https://developer.mozilla.org/en-US/docs/Web/API/AudioWorkletGlobalScope
```

The `/*@devdoc` comments are JSDoc comments that get compiled into the SDK's developer docs using the `npm run devdoc` command.

2021-10-30 07:29 UTC, digisomni commented
Firefox: I've uploaded the latest revision to https://vircadia.dev/websdk/pr43/example/interface.html for testing against PR1415 (which is now closed) and my voice is deep and disembodied coming from the browser.

Chrome: Same results.

2021-10-30 12:20 UTC, namark commented
I can reproduce the issue in Chrome it's related to the channel count change. For some reason audioStreamSource reports 2 channels for the mic, so I guess the only reliable way to retrieve is the approach taken in AudioClient, will push a updated fix soon.

Firefox worked just fine for me, but probably because it's a bit weird on my system, doesn't properly detect the mic information, but it's consistent (or happens to be consistent) between AudioInput and AudioClient, so there was no problem with the audio.

2021-10-30 12:57 UTC, namark commented
Channel count fixed the deep voice, but for some reason I still get some reason I only get sound in right ear from Chrome now, will have to investigate further.

2021-10-30 23:07 UTC, namark commented
Seems like I'm getting the right ear only sound on master branch too using chrome, so could be some unrelated bug that's affecting my setup specifically.

2021-11-25 19:47 UTC, ctrlaltdavid requested changes

2021-11-25 19:47 UTC, ctrlaltdavid commented on src/domain/audio/AudioInput.ts
> +            this.#_audioContext = new AudioContext();
```suggestion
            // We work around by using a context without sample rate requirement and handling re-sampling in the input worklet.
            console.log("Use resampler to match sample rates.");
            this.#_audioContext = new AudioContext();
```
Log a comment to indicate that the warning logged is being addressed.

2021-11-25 19:55 UTC, ctrlaltdavid commented
I tested Edge and Firefox: Microphone input from SDK example app was heard in both ears from native client (running on same PC with mic muted in Interface). Note: The audio is positioned in space and I heard it in left ear / right ear balance according to which direction my native client avatar was facing.

Edge
```
[audioclient] Input device info: Default - Microphone (Realtek Audio), 1 channels, 48000Hz, 16 bits, echo cancellation on
```

Firefox
```
[audioclient] Input device info: Microphone (Realtek Audio), 8 channels, 0Hz, 0 bits, echo cancellation on
Connecting AudioNodes from AudioContexts with different sample-rate is currently not supported.
```
- The Firefox "Connecting AudioNodes from ..." message indicates that the resampling code was used.
- The 0hz and 0bits values are just informative - I checked and Firefix doesn't provide these,. at least not for my audio card).

Note that my sound card at 48kHz is an integer multiple of Vircadia's 24kHz audio sample rate. Need to test with a sound card that isn't an integer multiple.

2021-11-26 19:08 UTC, ctrlaltdavid approved these changes

2021-11-26 21:43 UTC, ctrlaltdavid commented
I retested on Edge and Firefox, and the audio in both behave the same: SDK mic input is heard left / in front / right per listener orientation relative to SDK avatar source. I.e., working OK for me.

2021-11-29 04:54 UTC, digisomni approved these changes
Works for me.

2021-11-29 04:54 UTC, merged