Overriding properties of test.config.json with environment variables.
vircadia/vircadia-web-sdk pull request #70
Opened 2021-12-01 21:12 UTC by namark

2021-12-02 22:29 UTC, digisomni commented
Can we get it documented in the README the possible environment variables that can be used with testing? We should keep an up to date list there or in the SDK docs.

2021-12-02 23:08 UTC, namark commented
It's the same as what's in test.config.json just with a prefix, I guess we can turn it into js file and add jsdoc comments in it? The socket URLs are pretty straight forward, but I'm not sure I can explain the domain url properly.

2021-12-03 04:30 UTC, ctrlaltdavid requested changes
Looks good otherwise.

2021-12-03 04:30 UTC, ctrlaltdavid commented on README.md
> +`localhost` or other location specified in `./tests/test.config.json`. The location and other values of the config JSON can be overridden with environment variables, using the same property names, bu
Line too long. (Should be max 128 chars.)

2021-12-03 06:24 UTC, digisomni approved these changes
It's fine for now, we can do that when the file becomes bigger and the SDK becomes more complex.

2021-12-03 07:16 UTC, ctrlaltdavid approved these changes

2021-12-03 07:20 UTC, merged