Request entity data
vircadia/vircadia-web-sdk pull request #98
Opened 2022-05-09 12:08 UTC by julien-me

Request entity data from the entity server.

- [x] Add an `EntityQuery` class with a `write()` method.
- [x] Add an `EntityServer` class with `update()` and `queryOctree()` methods. 
- [x] Add an `OctreeQuery` class and implement it just enough to satisfy the needs of the above.
- [x] Add `packFloatAngleToTwoByte()` and `packClipValueToTwoByte()` to the class `GLMHelpers`.
- [x] Add a `ConicalViewFrustrum` class and implement it just enough to satisfy the needs of the above.
- [x] Update the example app with a game loop for the entity server.
- [x] Confirm receipt at entity server through instrumentation.

2022-05-09 23:05 UTC, ctrlaltdavid requested changes

2022-05-09 23:05 UTC, ctrlaltdavid commented on tests/domain/networking/packets/EntityQuery.unit.test.js
> +        data.conicalViews.at(0).radius = 3;
These values should really be set via an `octreeQuery.setConicalViews()` method.

2022-05-09 23:05 UTC, ctrlaltdavid commented on tests/domain/shared/GLMHelpers.unit.test.js
> +        const angle = 45.2;
Can angles also be negative? If so also test a negative value.

2022-05-10 07:49 UTC, julien-me commented on src/domain/networking/packets/EntityQuery.ts
> +        // WEBRTC TODO: Pack jsonParameters.
But in the C++ code bytes are written only when `_jsonParameters` isn't empty.
Here: https://github.com/vircadia/vircadia/blob/9f708e3c564e6aee41988778085863cd4c6fe185/libraries/octree/src/OctreeQuery.cpp#L79-L82

And I believe that `OctreeQuery::parseData(ReceivedMessage& message)` is the method used to unpack the data. If so then it tries to read the JSON parameters data only if `binaryParametersBytes` (length of `_jsonParameters`) is greater than 0.
Here: https://github.com/vircadia/vircadia/blob/9f708e3c564e6aee41988778085863cd4c6fe185/libraries/octree/src/OctreeQuery.cpp#L150-L161

If what you say is true, that JSON parameters are used only by the avatar mixer and server-side scripts, then I guess that we can simply ignore the JSON parameters in `EntityQuery.write()` and remove this TODO? :thinking:

2022-05-10 09:00 UTC, ctrlaltdavid commented on src/domain/networking/packets/EntityQuery.ts
> +        // WEBRTC TODO: Pack jsonParameters.
Yes, that's what I'm thinking: remove the TODO. But also add an `assert()` that the JSON parameters object is empty  / number of keys is 0. And in the JSDoc for `EntityQueryDetails` included a comment, "not used client-side".

2022-05-10 09:40 UTC, julien-me commented on src/domain/networking/packets/EntityQuery.ts
> +        // WEBRTC TODO: Pack jsonParameters.
:+1:

2022-05-10 19:49 UTC, ctrlaltdavid requested changes
Also, JSDoc for EntityQuery packet needed in PacketHeaders.ts.

2022-05-10 19:49 UTC, ctrlaltdavid commented on src/domain/networking/packets/EntityQuery.ts
> +    numFrustums: number,
This property isn't necessary: the number is the same as the length of the array of frustums.

2022-05-10 19:49 UTC, ctrlaltdavid commented on src/domain/octree/OctreeConstants.ts
> +        return 32768; // ~20 miles..
```suggestion
        return 32768; // ~20 miles.

```

2022-05-10 19:49 UTC, ctrlaltdavid commented on src/domain/octree/OctreeQuery.ts
> + *  @param {boolean} randomizeConnectionID - To assign, or not, a random number to the connectionID
```suggestion
 *  @param {boolean} randomizeConnectionID - <code>true</code> to use a random number for the initial connection ID, <code>false</code> to start at <code>0</code>.
```

2022-05-10 19:49 UTC, ctrlaltdavid commented on src/domain/networking/packets/EntityQuery.ts
> +     *  Information returned by {@link PacketScribe|writing} a {@link PacketType(1)|EntityQuery} packet.
```suggestion
     *  Information needed for {@link PacketScribe|writing} a {@link PacketType(1)|EntityQuery} packet.

```

2022-05-10 19:49 UTC, ctrlaltdavid commented on src/domain/networking/packets/EntityQuery.ts
> +     *  @property {Array<ConicalViewFrustum>} conicalViews - An array of conical frustums.
```suggestion
     *  @property {Array<ConicalViewFrustum>} conicalViews - An array of conical view frustums.

```

2022-05-10 20:27 UTC, ctrlaltdavid requested changes

2022-05-10 20:27 UTC, ctrlaltdavid commented on src/domain/octree/OctreeQuery.ts
> +     *  @param {Array<ConicalViewFrustum} views - An array of conical frustums.
```suggestion
     *  @param {Array<ConicalViewFrustum>} views - An array of conical frustums.

```

2022-05-11 03:56 UTC, ctrlaltdavid approved these changes

2022-05-11 06:56 UTC, merged